spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/cbts?user=postgres&password=948270

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    properties:
      hibernate:
        format_sql: true


# configuration for mail sender api
  mail:
    host: smtp.gmail.com
    port: 587
    username: deepaksharma948270@gmail.com
    password: cavujxnxcgygkdyy
    properties:
     mail:
      smtp:
       auth: true
       starttls:
        enable: true
    



